### ISSUE TITLE
doesn't load 

### ISSUE THREAD

**Issue by gucciflipflops725** [ThatFruedDued/blooket-utility#28]
when I launch prefs its just a white screen

<img width="1439" alt="Screen Shot 2021-10-28 at 6 04 57 PM" src="https://user-images.githubusercontent.com/93261565/139342775-eef3e617-3512-41a3-9417-be3f9aa3d50b.png">

**Comment by VirtualFiber415** [comment]
with isnt an issue just go to discover click search with nothing in the box and go back and every thing should load it work for me

**Comment by wolfgoo** [comment]
???
