### ISSUE TITLE
Everything works, EXCEPT CRYPTO!!!!

### ISSUE THREAD

**Issue by Scpwolf123** [ThatFruedDued/blooket-utility#30]
![image](https://user-images.githubusercontent.com/70712351/139584352-8a55ef3f-a84c-4311-9585-38e31c3ec147.png)
The crypto amount is not showing on the host screen, nor the "end of the game screen"

And all other games work perfectly...![image](https://user-images.githubusercontent.com/70712351/139584368-d0e9466e-afed-42aa-b982-20237b17717e.png)

**Comment by wolfgoo** [comment]
?

**Comment by Scpwolf123** [comment]
The hack wont show the amount of token u have in crypto
