### ISSUE TITLE
All Answers Correct - not working

### ISSUE THREAD

**Issue by hecker7734** [ThatFruedDued/blooket-utility#32]
# All Answers Correct doesn't work
Is All Answers Correct for a certain gamemode or?  it doesn't work at all even in solo or public matches.

**Comment by wolfgoo** [comment]
it just gives you a score or money.

**Comment by wolfgoo** [comment]
But you answers also wrong.

**Comment by hecker7734** [comment]
that's misleading, then it would be "extra score" or something...
