### ISSUE TITLE
custom maps dont work

### ISSUE THREAD

**Issue by VirtualFiber415** [ThatFruedDued/blooket-utility#33]
the map image doesnt load, enemies dont spawn, cant place towers, and just show loading forever in the top left
is the same issue for both maps

**Comment by VirtualFiber415** [comment]
also how do i set this to a bug im very new to github and trying to learn other code languages besides scratch

**Comment by wolfgoo** [comment]
?

**Comment by wolfgoo** [comment]
I can place towers, enemies will spawn after I used the custom maps.
