### ISSUE TITLE
Hi I can join and get in and j see select bloom and then it kicks me out

### ISSUE THREAD

**Issue by Fe4RLess1457** [ThatFruedDued/blooket-utility#40]
I join and I see select blook for like half a second and then I’m kicked out

**Comment by wolfgoo** [comment]
hmm, I aslo.

**Comment by wolfgoo** [comment]
I think have the bug?

**Comment by wolfgoo** [comment]
yes, it really has bug.

**Comment by HackersRnotCool** [comment]
Same bro i like join a game then put my user and it kicks me out instantly im not sure but my theory is that blooket is starting to detect the in game hacks.

**Comment by 914865** [comment]
Not for me
