### ISSUE TITLE
I know this sounds stupid but...

### ISSUE THREAD

**Issue by biggerblook** [ThatFruedDued/blooket-utility#50]
How do use the injectables? I got the window loader in but I can't figure out where to put the injectables. Can someone help me pls?

**Comment by ThatFruedDued** [comment]
Are you using https://blooket-utility.herokuapp.com? If so, please go to the https://blooket-utility.herokuapp.com/conf page. The window loader no longer functions due to Blooket updates, so I have moved on to ploader.
