### ISSUE TITLE
Heroku Application Error

### ISSUE THREAD

**Issue by BlooketHackerx** [ThatFruedDued/blooket-utility#51]
When I went to the link of the ploader it said application error. What do I do? Is it something I did?

**Comment by ThatFruedDued** [comment]
Hi, yes, this issue is known. It is due to Heroku limiting the amount of hours that free dynos are allocated to run. I will be fixing this soon and moving to my own server, so stay tuned!

**Comment by BlooketHackerx** [comment]
Thank you!! If you do need help covering the cost for a server, I may be of service, because I know how hard you have worked to keep the community happy and knowing that all those people who use your utility will be happy is plenty.

**Comment by ThatFruedDued** [comment]
The new URL is at https://blooket-utility.okr765.com. Please report any issues in a new issue.

**Comment by BlooketHackerx** [comment]
Thank you and how do you configurate it?

**Comment by ThatFruedDued** [comment]
Same way (https://blooket-utility.okr765.com/conf)

**Comment by BlooketHackerx** [comment]
Will there be any new injectables in the future? Just asking.

**Comment by ThatFruedDued** [comment]
Definitely! You can also develop your own injectables if you learn how (a guide may be made soon!).

**Comment by BlooketHackerx** [comment]
COOL! I can't wait!! btw nice update!!

**Comment by ThatFruedDued** [comment]
Thanks!
