### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by TeachMeHowHack** [ThatFruedDued/blooket-utility#61]
Can you add Google Login to your utility website? 
It says: Authorization Error
Error 400: redirect_uri_mismatch
You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.
If you're the app developer, register the JavaScript origin in the Google Cloud Console.
I kinda sorta forgot my pass and I can't login to it.
Thanks :)

**Comment by ThatFruedDued** [comment]
Hello, Sign In With Google cannot and will not be added to the utility. Please reset your Blooket password, then check your email if you do not remember your Blooket password and use that to log in.
