### ISSUE TITLE
is it broken?

### ISSUE THREAD

**Issue by kiwi334334** [ThatFruedDued/blooket-utility#62]
![Screenshot 2022-02-14 12 50 29 PM](https://user-images.githubusercontent.com/99292273/153935973-1a6bfb8f-3b55-4a9c-bdbd-ae12f7d116ea.png)

i'm really confused

**Comment by ThatFruedDued** [comment]
Thank you for reporting this issue. This issue is due to clashing styles between the Blooket Utility GUI and the Blooket website. This will be addressed soon.

**Comment by ThatFruedDued** [comment]
Fixed.
