### ISSUE TITLE
will you write some code and coordinate with thyme the person who created the multi tool blooket hack and make it work for your clone website

### ISSUE THREAD

**Issue by kiwi334334** [ThatFruedDued/blooket-utility#63]
thank you

**Comment by ThatFruedDued** [comment]
Are you talking about Basil?

**Comment by kiwi334334** [comment]
yes

**Comment by kiwi334334** [comment]
sorry i forgot his name

**Comment by kiwi334334** [comment]
since this is already open can i talk to you about if there are any other hacks that work with this sandboxed website

**Comment by ThatFruedDued** [comment]
@kiwi334334 if you want to talk about that, you can contact me on Discord by joining my server (learn more at <https://okr765.com/discord>). I don't feel comfortable implementing Basil's scripts right now because there have been bans regarding those scripts reported recently.
