### ISSUE TITLE
invaled injectables

### ISSUE THREAD

**Issue by pazza223** [ThatFruedDued/blooket-utility#66]
nomater what i do, I can not find a way to get it to work. it will always give me that error. I am trying to find a alt to gliz's hacks after he got band and thoght that these where good, if you think that there is a better alt for hacks or is there a way to fix this. I got on to github, saw that gliz was band, and have no idea what to do...

**Comment by ThatFruedDued** [comment]
There is not currently a feature-compelte alternative to Glixzzy's scripts. I may work on this in the future.
