### ISSUE TITLE
You just piggyback off of other peoples scripts.

### ISSUE THREAD

**Issue by Belook12** [ThatFruedDued/blooket-utility#75]
This developer just uses other people's scripts so he can inject their scripts into his "blooket utility".

**Comment by hxc4life07** [comment]
No, you are wrong. He cloned the api of blooket and the entire web. He created the injectables, but glixzzy's injectable, well, he created the injectable but used other code

**Comment by hxc4life07** [comment]
So, if you don't know about programming and coding, just shut up...

**Comment by ThatFruedDued** [comment]
@Belook12 Please do not spread false rumors about me. I have **never** stolen scripts from other people. I have, however, used glixzzy's scripts by incorporating them into a injectable that works with this Blooket Utility, but I credited glixzzy entirely for that injectable (even though I built the UI for it and the script loading system). I have spent hours and hours of my time designing and developing the injection system that my Blooket Utility uses. Also, unlike all other working scripts, it is completely 100% open source, which makes this very difficult to monetize. Your ignorance is insulting to me as a developer, as I spend *my* time to help *you*, receive *no* financial compensation, and I am then accused of stealing other people's scripts. Again, please do not spread misinformation like this, as it is very discouraging to me.

**Comment by kgsensei** [comment]
> This developer just uses other people's scripts so he can inject their scripts into his "blooket utility".

There is no issue with using other people's scripts to help in your own projects. This is GitHub, it's literally open-source software.
