### ISSUE TITLE
Dosent work now?

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [ThatFruedDued/blooket-utility#76]
Um, the Blooket utility doesn't work right now. I don't know how to explain it but when I go to the blooket utility website it says in the URL https://dashboard.blooket.com/market. instead of https://blooket-utility.okr765.com/market

**Comment by ThatFruedDued** [comment]
Yes, this issue is known and is top priority. I will be working on this as soon as possible.

**Comment by Snowflake-Coder-H2o** [comment]
@ThatFruedDued Thank you Okr765

**Comment by ThatFruedDued** [comment]
This has been fixed.
