### ISSUE TITLE
give 500 coins

### ISSUE THREAD

**Issue by Aethese** [ThatFruedDued/blooket-utility#8]
you can give yourself up to 500 coins daily with [this](https://github.com/glixzzy/blooket-hack/blob/main/global/addTokens.js) script made by [glixzzy](https://github.com/glixzzy). you should add this into your program (should be easy as the source isn't obfed)

**Comment by ThatFruedDued** [comment]
Yeah I probably will add this soon, adding tokens isn't very difficult.

**Comment by VirtualFiber415** [comment]
is there a way to get it to give more than 500 tokens and 300xp?

**Comment by wolfgoo** [comment]
Go to https://github.com/glixzzy/blooket-hack.

**Comment by memegreen123** [comment]
can someone paste the code in the comments  my school blocked it so i cant go to https://github.com/glixzzy/blooket-hack

**Comment by TeachMeHowHack** [comment]
Copy the whole thing

**Comment by ThatFruedDued** [comment]
Your comment was hidden due to its length.

**Comment by SushiMikatsuX** [comment]
uhh it's not working

**Comment by hiiiii321** [comment]
It sucks that Ben added an upgrade to Blooket to block all hacks:( (GitHub is my favorite hack maker)

**Comment by 1rainbowfruitlover1** [comment]
bruh what happened to gliz's javascript?????

**Comment by OnePunchKid88** [comment]
it not work

**Comment by timekeepercookie** [comment]
gliz got a cease and desist from blooket thats why its not working yall (to the people who said its not working)

**Comment by 1rainbowfruitlover1** [comment]
> gliz got a cease and desist from blooket thats why its not working yall (to the people who said its not working)

well could someone else make another JavaScript for more coins?

**Comment by ThatFruedDued** [comment]
Currently, the easiest way to get coins is through my [Discord server](https://discord.io/okr765), but I may add it to the utility in the future.

**Comment by derinpilge** [comment]
> bruh what happened to gliz's javascript?????

He sold it to school cheats

**Comment by SushiMikatsuX** [comment]
bro

**Comment by paxman12345678910** [comment]
my class loves to get every single blook

**Comment by qwertymok** [comment]
got pink astro with the 500 tokens
happy thx guys

**Comment by I91C** [comment]
how do you use this

**Comment by mseeeeeeeeeeee** [comment]
can yall put the code so i can c and p 😢

**Comment by ThatFruedDued** [comment]
Discussing alternate Blooket scripts is permitted here, but copy/pasting them floods the thread and is not permitted.

**Comment by LoveTheWorld10** [comment]
Is there a way to add tokens without using isnspect?
