### ISSUE TITLE
blooket injectables not working

### ISSUE THREAD

**Issue by mmarchjr** [ThatFruedDued/blooket-utility#84]
I am working on my own injectable following the glixxzy cheat one. when I do the konami code to open it however, it is just a blank box with no text. Could you please tell me what I did wrong?
![image](https://user-images.githubusercontent.com/103056947/167673218-e7f06fe6-2af7-40fc-97aa-82c7ce2d5285.png)
the link to the repository containing the injectable is 
https://github.com/mmarchjr/blooket-anti-cheat-tester

**Comment by ThatFruedDued** [comment]
The Utility can have issues loading from `raw.githubusercontent.com` domains. Please set up GitHub Pages and load your JavaScript files from the `github.io` domain instead.
