### ISSUE TITLE
it takes me to the sign in page

### ISSUE THREAD

**Issue by ufehurh** [ThatFruedDued/blooket-utility#87]
if i then try to leave that page it takes me to the normal page. I cant join a game or sign in.is there a way to join a game or a url that takes you to join a game?

**Comment by ThatFruedDued** [comment]
If you are attempting to sign in with Google, please first sign into <https://dashboard.blooket.com>, add a Blooket password to your account, then sign in using that. **It is not possible to integrate with Google services without permission from Blooket which won't happen.**

**Comment by VillainsRule4000** [comment]
@ThatFruedDued FINALLY RESOLVING ISSUES THANK YOU SO MUCH

**Comment by ThatFruedDued** [comment]
Duplicate of #59
